language: node_js
node_js:
- '5.0'
env:
  global:
    secure: WlwI+twHR0xR0YQoWH/GGudHSwNaZZT8yTSlvSQQOhqaLabltB87eCiTDprPnKSNZScJpRJ6Iu3RVEQe4Oey1ikOtDeZ69eFIEZiXsxlFfYQ5h4VbDYnOVaRv67j9vWJTwYVx5K+Gf3qTU3Z8AuXhnqFPYXjIGBiHBsbo0lA8fvMaKuT1OOa7fwGyQ29BMwTtlCD11+OWUc4/vI9i3Iv5nrpJRf8YQu8M/42XmkQv2gUSj3FyPk0XAnYnmgsVP4OmrL4dw6CPV0ISGTxm7SV/9HQFt/AXZaAd9F3ZS3xzzLNYdPgQ1Q3Ksmi+6YFC7yfeKl1Odik8BGAvPKWo1qHi2n3zy99cwG25aO0yLKwt0kX2U3LACUShXcGT+924BaM1l+I592rEefnyGhV8Xz5U3n/kI6/SM/Tp1NvxcD/hW7FPW+go7BLlT0TNq/fg6glAOmuty0VBFyDCexWuEbSLvZm0l/mKvIz1pHddORdms0mRO0xxKjSgVS4BoAHTJBzhYiGTLe8b4jPRaAbFLcudCLMGel6qRPFmSv7dOW9duqIkCUdZpVsP4uMsB45zXIZnRIawIwoxpwSQrAnjSuzZsBCaylFJo9KZjz35K3YPNdQ8W7BeFm/3TvsNkFSSIbqtd+f/I3CwFA7kUB7n/Q5manOCFND5mbvUdo5sf+Xj1Y=
